os:
  - linux
# would be nice to check build with osx
#  - osx

language:
  - cpp

compiler:
  - gcc

addons:
  apt:
    packages:
    - g++-5
    - gcc-5
    - make
    - cmake
    - binutils-dev
    - libgtk2.0-dev
    - libois-dev
    - libogre-1.9-dev
    - libexpat-dev
    - libfreetype6-dev
    - libsfml-dev
    - libopenal-dev

before_install:
  - wget http://prdownloads.sourceforge.net/crayzedsgui/cegui-0.8.4.tar.bz2?download -O - | tar xz
  - (cd cegui-0.8.4 && cmake . && sudo make install)
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake -DCMAKE_BUILD_TYPE=Release && make; fi

cache: apt
