language: cpp

sudo: required
dist: trusty

os:
  - linux

compiler:
  - gcc

before_install:
  - gcc --version
  - sudo apt-get update -qq
# OD dependencies
  - sudo apt-get install -y cmake pkg-config libogre-1.9-dev libopenal-dev libsfml-dev libois-dev
  - sudo apt-get install -y libboost-filesystem-dev libboost-locale-dev libboost-program-options-dev libboost-date-time-dev libboost-thread-dev libboost-system-dev libboost-test-dev
# Install CEGUI from GetDeb
  # GetDeb repo is down, can't find the key anymore
  # We can however still use its MegaGlest mirror for now
  #- wget -q -O - http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
  - sudo sh -c 'echo "deb http://getdeb.megaglest.org/ubuntu trusty-getdeb games" >> /etc/apt/sources.list.d/getdeb.list'
  - sudo apt-get update -qq --allow-unauthenticated; sudo apt-get install -y --allow-unauthenticated libcegui-0.8-dev

script:
  - cmake . -DOD_BUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release
  - make -j2
  - make install DESTDIR=./install-root
  - ./scripts/unix/run_unit_tests.sh
